language: scala
dist: trusty
jdk:
  - oraclejdk8

scala:
  - 2.13.6

branches:
  only:
    - master

script: sbt ++$TRAVIS_SCALA_VERSION -Dsbt.log.noformat=false clean test

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - $HOME/.cache/coursier
    - $HOME/.m2

before_install:
  - export TZ=Asia/Shanghai